---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backup-sa
  namespace: benchmark-system

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: backup-role
  namespace: benchmark-system
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/exec"]
    verbs: ["get", "list", "create"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind:RoleBinding
metadata:
  name: backup-rolebinding
  namespace: benchmark-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: backup-role
subjects:
  - kind: ServiceAccount
    name: backup-sa
    namespace: benchmark-system

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backup-config
  namespace: benchmark-system
data:
  NAMESPACE: "benchmark-system"
  POSTGRES_POD: "postgres-0"
  BACKUP_BUCKET: "benchmark-backups"
  RETENTION_DAYS: "30"

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: database-backup
  namespace: benchmark-system
spec:
  # Run daily at 2 AM UTC
  schedule: "0 2 * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 7
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: database-backup
        spec:
          serviceAccountName: backup-sa
          restartPolicy: OnFailure
          containers:
            - name: backup
              image: ghcr.io/your-org/service-mesh-benchmark/backup:latest
              imagePullPolicy: Always
              envFrom:
                - configMapRef:
                    name: backup-config
              env:
                - name: OCI_CLI_AUTH
                  value: "instance_principal"
                - name: OCI_COMPARTMENT_ID
                  valueFrom:
                    secretKeyRef:
                      name: oci-credentials
                      key: compartment_id
              volumeMounts:
                - name: backup-script
                  mountPath: /scripts
                - name: oci-config
                  mountPath: /root/.oci
                  readOnly: true
              command:
                - /bin/bash
                - /scripts/backup-to-oci.sh
              resources:
                requests:
                  cpu: 100m
                  memory: 256Mi
                limits:
                  cpu: 500m
                  memory: 512Mi
          volumes:
            - name: backup-script
              configMap:
                name: backup-scripts
                defaultMode: 0755
            - name: oci-config
              secret:
                secretName: oci-credentials
                defaultMode: 0600
