---
# Service Account for workload pods
# Minimal permissions for running workload applications
apiVersion: v1
kind: ServiceAccount
metadata:
  name: workload-sa
  namespace: default
  labels:
    app: workload
automountServiceAccountToken: false  # Don't mount token unless needed
---
# Role for workload operations (if needed)
# Currently empty - workloads don't need K8s API access
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: workload-minimal
  namespace: default
  labels:
    app: workload
rules: []  # No permissions - workloads should not access K8s API
---
# RoleBinding (for future use if permissions are needed)
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: workload-minimal
  namespace: default
  labels:
    app: workload
subjects:
- kind: ServiceAccount
  name: workload-sa
  namespace: default
roleRef:
  kind: Role
  name: workload-minimal
  apiGroup: rbac.authorization.k8s.io
