---
apiVersion: v1
kind: Namespace
metadata:
  name: benchmark-system
  labels:
    name: benchmark-system
    purpose: infrastructure

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: benchmark-system
data:
  POSTGRES_DB: service_mesh_benchmark
  POSTGRES_USER: benchmark

---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: benchmark-system
type: Opaque
stringData:
  POSTGRES_PASSWORD: "ChangeMeInProduction!"  # Change this!
  DATABASE_URL: "postgresql://benchmark:ChangeMeInProduction!@postgres-service.benchmark-system.svc.cluster.local:5432/service_mesh_benchmark"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: benchmark-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: oci-bv  # Oracle Cloud Block Volume

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: benchmark-system
spec:
  serviceName: postgres-service
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      securityContext:
        runAsUser: 999  # Postgres user
        runAsGroup: 999
        fsGroup: 999
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
              name: postgres
          envFrom:
            - configMapRef:
                name: postgres-config
            - secretRef:
                name: postgres-secret
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
              subPath: postgres
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1Gi
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - benchmark
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - benchmark
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: benchmark-system
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
  clusterIP: None  # Headless service for StatefulSet
