---
# Baseline gRPC service without service mesh for performance comparison
apiVersion: v1
kind: Namespace
metadata:
  name: baseline-grpc
  labels:
    workload-type: grpc
    mesh: none
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: baseline-grpc-server
  namespace: baseline-grpc
  labels:
    app: baseline-grpc-server
    workload: baseline
spec:
  replicas: 3
  selector:
    matchLabels:
      app: baseline-grpc-server
  template:
    metadata:
      labels:
        app: baseline-grpc-server
        version: v1
    spec:
      containers:
      - name: grpcbin
        image: moul/grpcbin:latest
        ports:
        - containerPort: 9000
          name: grpc
        - containerPort: 9001
          name: grpc-web
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi
        livenessProbe:
          tcpSocket:
            port: 9000
          initialDelaySeconds: 10
          periodSeconds: 5
        readinessProbe:
          tcpSocket:
            port: 9000
          initialDelaySeconds: 5
          periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: baseline-grpc-server
  namespace: baseline-grpc
  labels:
    app: baseline-grpc-server
spec:
  type: ClusterIP
  ports:
  - port: 9000
    targetPort: 9000
    protocol: TCP
    name: grpc
  selector:
    app: baseline-grpc-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: baseline-grpc-client
  namespace: baseline-grpc
  labels:
    app: baseline-grpc-client
spec:
  replicas: 2
  selector:
    matchLabels:
      app: baseline-grpc-client
  template:
    metadata:
      labels:
        app: baseline-grpc-client
        version: v1
    spec:
      containers:
      - name: grpcurl
        image: fullstorydev/grpcurl:latest
        command: ["/bin/sh"]
        args:
          - -c
          - |
            while true; do
              grpcurl -plaintext -d '{"greeting": "hello"}' \
                baseline-grpc-server.baseline-grpc.svc.cluster.local:9000 \
                hello.HelloService.SayHello || true
              sleep 1
            done
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: baseline-grpc-server-nodeport
  namespace: baseline-grpc
  labels:
    app: baseline-grpc-server
spec:
  type: NodePort
  ports:
  - port: 9000
    targetPort: 9000
    nodePort: 30091
    protocol: TCP
    name: grpc
  selector:
    app: baseline-grpc-server
