---
apiVersion: v1
kind: Namespace
metadata:
  name: http-benchmark
  labels:
    workload-type: http
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: http-benchmark
data:
  nginx.conf: |
    worker_processes auto;
    events {
      worker_connections 1024;
    }
    http {
      access_log /var/log/nginx/access.log;
      error_log /var/log/nginx/error.log;

      server {
        listen 80;
        location / {
          return 200 'HTTP Benchmark Response\n';
          add_header Content-Type text/plain;
        }
        location /health {
          return 200 'OK';
        }
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-server
  namespace: http-benchmark
  labels:
    app: http-server
    workload: benchmark
spec:
  replicas: 3
  selector:
    matchLabels:
      app: http-server
  template:
    metadata:
      labels:
        app: http-server
        version: v1
    spec:
      # Pod-level security context
      securityContext:
        runAsNonRoot: true
        runAsUser: 101  # nginx user in alpine
        runAsGroup: 101
        fsGroup: 101
        seccompProfile:
          type: RuntimeDefault

      containers:
      - name: nginx
        image: nginx:alpine
        # Container-level security context
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 101
          capabilities:
            drop:
              - ALL
            add:
              - NET_BIND_SERVICE  # Required for binding to port 80
        ports:
        - containerPort: 80
          name: http
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        - name: nginx-cache
          mountPath: /var/cache/nginx
        - name: nginx-run
          mountPath: /var/run
        - name: nginx-logs
          mountPath: /var/log/nginx
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 3

      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config
      - name: nginx-cache
        emptyDir: {}
      - name: nginx-run
        emptyDir: {}
      - name: nginx-logs
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: http-server
  namespace: http-benchmark
  labels:
    app: http-server
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: http-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-client
  namespace: http-benchmark
  labels:
    app: http-client
spec:
  replicas: 2
  selector:
    matchLabels:
      app: http-client
  template:
    metadata:
      labels:
        app: http-client
        version: v1
    spec:
      # Pod-level security context
      securityContext:
        runAsNonRoot: true
        runAsUser: 100  # curl user
        runAsGroup: 101
        fsGroup: 101
        seccompProfile:
          type: RuntimeDefault

      containers:
      - name: curl
        image: curlimages/curl:latest
        # Container-level security context
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 100
          capabilities:
            drop:
              - ALL
        command: ["/bin/sh"]
        args:
          - -c
          - |
            while true; do
              curl -s http://http-server.http-benchmark.svc.cluster.local/
              sleep 1
            done
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi

      volumes:
      - name: tmp
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: http-server-nodeport
  namespace: http-benchmark
  labels:
    app: http-server
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
    protocol: TCP
    name: http
  selector:
    app: http-server
