---
apiVersion: v1
kind: Namespace
metadata:
  name: websocket-benchmark
  labels:
    workload-type: websocket
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: websocket-server
  namespace: websocket-benchmark
  labels:
    app: websocket-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: websocket-server
  template:
    metadata:
      labels:
        app: websocket-server
        version: v1
    spec:
      containers:
      - name: websocket-echo
        image: jmalloc/echo-server:latest
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: PORT
          value: "8080"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: websocket-server
  namespace: websocket-benchmark
  labels:
    app: websocket-server
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: websocket-server
---
apiVersion: v1
kind: Service
metadata:
  name: websocket-server-nodeport
  namespace: websocket-benchmark
  labels:
    app: websocket-server
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30808
    protocol: TCP
    name: http
  selector:
    app: websocket-server
